# /home/andy/infra/ansible/playbooks/roles/traefik/tasks/main.yml
---
- name: Create traefik docker network
  docker_network:
    name: traefik
    driver: bridge
    state: present

- name: Create traefik container
  docker_container:
    name: traefik
    image: traefik:v2.11
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/andy/infra/data/traefik/acme:/etc/traefik/acme"
      - "/home/andy/infra/data/traefik:/etc/traefik/dynamic"
    networks:
      - traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsEncrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsEncrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsEncrypt.acme.email=andy@geller.men"
      - "--certificatesresolvers.letsEncrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--log.level=INFO"
      - "--accesslog=true"
