# Hostvars f√ºr erweckedeinekraft.de

domain: erweckedeinekraft.de

traefik:
  domain: erweckedeinekraft.de
  aliases:
    - www.erweckedeinekraft.de

# ghost_mysql:
ghost_domain_db: ghost_erweckedeinekraft_de
ghost_domain_usr: ghost_erweckedeinekraft_de_usr
ghost_domain_pwd: e51c10ee65d443b776a1300e2f8a5f88

ghost_env: production
